name: Python Script Scheduler  # 워크플로우 이름

on:
  schedule:
    - cron: '0 9 * * *'  # 매일 오전 9시 (UTC)
    - cron: '0 12 * * *' # 매일 정오 (UTC)
    - cron: '0 18 * * *' # 매일 오후 6시 (UTC)
    - cron: '0 3 * * *'  # 매일 새벽 3시 (UTC)
  workflow_dispatch: # 수동 트리거 활성화

jobs:
  run_python_script:
    runs-on: ubuntu-latest  # 실행 환경 (Ubuntu 최신 버전)
    steps:
      - uses: actions/checkout@v3  # 코드 체크아웃
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # 사용할 Python 버전
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # requirements.txt가 있는 경우
      - name: Set environment variables
        run: |
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
      - name: Run Python script
        run: python news_scrap.py  # 실제 스크립트 이름으로 변경
      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update data (automated)"
          file_pattern: articles_filtered.json  # 커밋할 파일
