name: Python Script Scheduler

on:
  schedule:
    - cron: '40 20 * * *'  # 한국 시간 오전 5시 40분 (UTC 20시 50분)
    - cron: '0 04 * * *'  # 한국 시간 오후 1시 (UTC 04시)
    - cron: '0 08 * * *'  # 한국 시간 오후 5시 (UTC 08시)
  workflow_dispatch:

permissions:
  contents: write  # 쓰기 권한 부여

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download NLTK data
        run: |
          python -m nltk.downloader punkt
      - name: Set environment variables
        run: |
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
      - name: Run Python script
        run: python news_scrap.py
      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update data (automated)"
          file_pattern: articles_filtered_*.json
