name: Python Script Scheduler

on:
  schedule:
    - cron: '0 0 * * *'    # 매일 0시 (UTC) -> 한국 시간 09시
    - cron: '4 4 * * *'    # 매일 4시 4분 (UTC) -> 한국 시간 13시 4분
    - cron: '8 8 * * *'    # 매일 8시 8분 (UTC) -> 한국 시간 17시 8분
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download NLTK data
        run: |
          python -m nltk.downloader punkt
      - name: Set environment variables
        run: |
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
      - name: Run Python script
        run: python news_scrap.py
      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update data (automated)"
          file_pattern: articles_filtered_*.json
